jobs:
  build:
    docker:
      - image: 'csarko/node_terraform_awscli'
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install dependencies
          command: npm ci
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
          - ./node_modules
      - run: npm run build
      - aws-s3/sync:
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"
          aws-access-key-id: ${AWS_ACCESS_KEY_ID}
          aws-region: us-east-1
          aws-secret-access-key: ${AWS_SECRET_ACCESS_KEY}
          from: bucket
          overwrite: true
          to: 's3://webgl.csarko.sh'
orbs:
  aws-s3: circleci/aws-s3@x.y
version: 2.1
